- arguments: [ --cross, --threads ]
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- ignore: { name: Use lambda-case }
- ignore: { name: Use <|> }
- ignore: { name: Use &&& }
