addons:
  apt:
    packages:
    - libgmp-dev
  code_climate:
    repo_token: f3ec70e01eb3f7fae0d1b61099d4ea64573c23e5a66bd34b9d6c2a1870ea5b63
after_success:
- stack tools/upload-package.hs
- stack tools/attach-binary.hs
before_install:
- sh tools/install-stack.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
env:
  global:
  - HACKAGE_USERNAME=fozworth
language: c
os:
- linux
- osx
script:
- stack setup
- stack build --ghc-options -O2 --only-dependencies --test
- stack build --ghc-options -O2 --pedantic --test --test-arguments '--match 29F5'
- stack sdist
