addons:
  apt:
    packages:
    - libgmp-dev
  code_climate:
    repo_token: f3ec70e01eb3f7fae0d1b61099d4ea64573c23e5a66bd34b9d6c2a1870ea5b63
after_success:
- stack tools/upload-package.hs
- stack tools/attach-binary.hs
before_install:
- sh tools/install-stack.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
env:
  global:
  - HACKAGE_USERNAME=fozworth
  # GITHUB_TOKEN
  - secure: LO2wmj44Bso3acH2V5emMrLzBy26xyhRlaqWQd2Rdph9tkOv2PhXX05T9EeULnLKqUlYJS6l4ocRBy/VGy4WSfF8lQz3IHtUGn0zwmzT9GsjxphfT/A+cfV3MsMSSv37n04XEEMi/X8EpnTweN01+2QOHpyBO6adJM0DiNJuxHXwSob3ZYO6T90cdjRcwHXEEFJoXkjRW1aYQFrecV5FpkhmdXLZ6MR0f8QjIjLFSqD3FjQ0KHIY5Lit5RtQyJ+v9mLsq82fEk5IsxyBUCnbjOC9cFJ7Ww10MdMQ/ylh92NgzB7ON835LLLPDPO1KFNm/oznUceOVZAswdUHsQSD6uVb/RvUNWxG1vnD4MFqNjTUNqxmb2qeUUmuvxAZObJRYix3Vn42U168HKWCR2GxWio4b8YXzEZrgIyFNeOXzESd3+/b+P2OGymf9ElDhFYP5PwYivSvj6PGbh1QPxLn7kSlBju0tGRxsduRYKmERBDR17EH1rq87aR9f7Hk1J1TaWHqP+i5N1/RtZN+AJ3P923VJTwha2Apqe2zGoVOzNmK6J3XkHgQI4f346GK9tecziS2YzpkBSkA7PbrEQTk8dWS2jXsev9X5Wr3AQ+xK652XMtyio2SSO+h1sLrrsHiGyvKy0NYfw3FK9i+7UiqJhkgRtU7P4OZurkDo+33igY=
language: c
os:
- linux
- osx
script:
- stack setup
- stack build --ghc-options -O2 --only-dependencies --test
- stack build --ghc-options -O2 --pedantic --test --test-arguments '--match 29F5'
- stack sdist
