cache:
- 'c:\\bin'
- 'c:\\stack -> stack.yaml'
clone_folder: 'c:\\rattletrap'
environment:
  GITHUB_TOKEN:
    secure: CTD2sGkh3EQaLuMJybGza6XNaI+Ews42mdNy9p3U+eShkrjIwYrbUVKnpzra8kIZ
  PATH: 'c:\\bin;%PATH%'
  STACK_ROOT: 'c:\\stack'
install:
- powershell -File tools/install-stack.ps1
- powershell -File tools/install-github-release.ps1
on_success:
- powershell -File tools/attach-binary.ps1
platform: x64
test_script:
- ps: 'stack setup | out-null'
- stack build --ghc-options -O2 --only-dependencies --test
- stack build --ghc-options -O2 --pedantic --test
- stack sdist --pvp-bounds both
version: '{build}'
