build: off
clone_folder: c:/rattletrap
environment:
  GITHUB_TOKEN:
    secure: TJVqbM1vZRfsmP7Tb98arfaAN+X/D9NpXUyVXJMog3iBKjC0q8gYshhk0b3dzCOy
  PATH: c:/bin;%PATH%
  STACK_ROOT: c:/stack
install:
- powershell -File tools/install-stack.ps1
on_success:
- stack --jobs 1 tools/attach-binary.hs
platform: x64
test_script:
- stack --jobs 1 setup > nul
- stack build --ghc-options -O2 --jobs 1 --only-dependencies --test
- stack build --ghc-options -O2 --jobs 1 --pedantic --test
- stack --jobs 1 sdist
version: '{build}'
