build: off
clone_folder: c:/rattletrap
environment:
  GITHUB_TOKEN:
    secure: CTD2sGkh3EQaLuMJybGza6XNaI+Ews42mdNy9p3U+eShkrjIwYrbUVKnpzra8kIZ
  PATH: c:/bin;%PATH%
  STACK_ROOT: c:/stack
install:
- powershell -File tools/install-stack.ps1
on_success:
- stack tools/attach-binary.hs
platform: x64
test_script:
- stack setup > nul
- stack build --ghc-options --jobs 1 -O2 --only-dependencies --test
- stack build --ghc-options --jobs 1 -O2 --pedantic --test
- stack sdist
version: '{build}'
