category: Game
description: Rattletrap parses and generates Rocket League replays.
executables:
  rattletrap:
    dependencies:
    - aeson
    - aeson-casing
    - base
    - binary
    - bytestring
    - rattletrap
    - template-haskell
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- HLint.hs
- README.markdown
ghc-options: -Wall
library:
  dependencies:
  - base
  - bimap
  - binary
  - binary-bits
  - bytestring
  - containers
  - data-binary-ieee754
  - regex-compat
  - text
  - vector
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: rattletrap
synopsis: Parse and generate Rocket League replays.
tests:
  lint:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Lint.hs
    source-dirs: test
  test:
    dependencies:
    - base
    - binary
    - bytestring
    - filepath
    - rattletrap
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Test.hs
    source-dirs: test
version: '0.0.0'
