category: Game
default-extensions:
- Strict
description: Rattletrap parses and generates Rocket League replays.
executables:
  rattletrap:
    dependencies:
    - aeson
    - base
    - binary
    - bytestring
    - rattletrap
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- HLint.hs
- README.markdown
- test/replays/*.replay
ghc-options: -Wall
github: tfausak/rattletrap
library:
  dependencies:
  - aeson >=0.11 && <1.1
  - aeson-casing >=0.1 && <0.2
  - base >=4.9 && <4.10
  - bimap >=0.3 && <0.4
  - binary >=0.8 && <0.9
  - binary-bits >=0.5 && <0.6
  - bytestring >=0.10 && <0.11
  - containers >=0.5 && <0.6
  - data-binary-ieee754 >=0.4 && <0.5
  - template-haskell >=2.11 && <2.12
  - text >=1.2 && <1.3
  - vector >=0.11 && <0.12
  other-modules: Paths_rattletrap
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: rattletrap
synopsis: Parse and generate Rocket League replays.
tests:
  lint:
    dependencies:
    - base
    - hlint >=1.9 && <1.10
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Lint.hs
    source-dirs: test
  test:
    dependencies:
    - base
    - bytestring
    - filepath >=1.4 && <1.5
    - rattletrap
    - tasty >=0.11 && <0.12
    - tasty-hspec >=1.1 && <1.2
    - temporary >=1.2 && <1.3
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Test.hs
    source-dirs: test
version: '0.3.0'
