resolver: ghc-8.2.1

extra-deps:
  - aeson-1.2.1.0
  - ansi-terminal-0.6.3.1
  - async-2.1.1.1
  - attoparsec-0.13.1.0
  - base-compat-0.9.3
  - bimap-0.3.3
  - binary-bits-0.5
  - call-stack-0.1.0
  - data-binary-ieee754-0.4.4
  - dlist-0.8.0.3
  - exceptions-0.8.3
  - hashable-1.2.6.1
  - hspec-2.4.4
  - hspec-core-2.4.4
  - hspec-discover-2.4.4
  - hspec-expectations-0.8.2
  - HUnit-1.6.0.0
  - integer-logarithms-1.0.2
  - mtl-2.2.1
  - old-locale-1.0.0.7
  - primitive-0.6.2.0
  - QuickCheck-2.10.0.1
  - quickcheck-io-0.2.0
  - random-1.1
  - scientific-0.3.5.1
  - setenv-0.1.1.3
  - stm-2.4.4.1
  - tagged-0.8.5
  - temporary-1.2.1
  - text-1.2.2.2
  - tf-random-0.5
  - time-locale-compat-0.1.1.3
  - transformers-compat-0.5.1.4
  - unordered-containers-0.2.8.0
  - uuid-types-1.0.3
  - vector-0.12.0.1

flags:
  time-locale-compat:
    old-locale: false
