name: rattletrap-tools
version: 1.0.0

dependencies:
  - base
  - bytestring
  - filepath
  - process
ghc-options: -Wall

executables:
  attach-binary:
    dependencies:
      - temporary
    main: attach-binary.hs
  upload-package:
    dependencies:
      - aeson
      - directory
      - text
    main: upload-package.hs
