name: rattletrap-tools
version: 1.0.0

dependencies:
  - base
  - bytestring
  - filepath
  - process
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe

executables:
  attach-binary:
    dependencies:
      - temporary
    main: attach-binary.hs
  upload-package:
    dependencies:
      - aeson
      - directory
      - text
    main: upload-package.hs
